### ISSUE TITLE
客户端多久上报一次？

### ISSUE THREAD

**Issue by badboycxcc** [huoji120/DuckSysEye#4]
本地搭建好后，一直没有数据，log已开启，如何判断客户端也没有上报？
server日志如下，一直都是这样。
![image](https://user-images.githubusercontent.com/72059221/184468498-62903f9a-d72a-41dc-963f-53dd4eab4ac4.png)

**Comment by huoji120** [comment]
看到webserver.py了么,打开它，注释掉这两行
flask_log = logging.getLogger('werkzeug')
flask_log.setLevel(logging.ERROR)
如果没有日志检查一下客户端ip是不是设置错了，能不能联得通啥的.

**Comment by badboycxcc** [comment]
flask_log = logging.getLogger('werkzeug')
flask_log.setLevel(logging.ERROR)
已经开启，log如上图所示。客户端是实时检测上报吗？

**Comment by huoji120** [comment]
那就是没有日志,你客户端安装了吗? 安装了在config.ini里面的服务端IP设置对了吗?
确认是否成功安装,在客户端那边打开任务管理器,看服务里面有没有两个服务正在运行中,一个是sysmon 一个是syseye,要确保这两个服务在运行中.

**Comment by huoji120** [comment]
我先关闭这个issue，诺还有问题再打开
