### ISSUE TITLE
一个小建议，能不能同步linux和mac端的工具出来，这个工具比较适合办公安全的检测响应

### ISSUE THREAD

**Issue by NuyOahIII** [huoji120/DuckSysEye#5]
一个小建议，能不能同步linux和mac端的工具出来，这个工具比较适合办公安全的检测响应

**Comment by huoji120** [comment]
这个想过,主要是我没太多时间,windows的目前还在做也没做完.一个人力量有限.等社区协作或者有空了再加一下
